settings:
  name: "NetApp container solutions"
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
    lipi_enabled: true
  pdf: 
    gen-type: named-only
    zip-level: 1
    zip-filename: netapp-solutions-containers.zip

product-family:
  name: NetApp solutions
  repo: netapp-solutions-family

sidebar:
  entries:
    - title: "Container solutions"
      url: /index.html
    - title: "What's new"
      url: /whats-new.html
    - title: Get started
      entries:
          - title: "About NetApp storage"
            url: /anthos/anthos-netapp-overview.html
          - title: "About NetApp ONTAP"
            url: /anthos/anthos-netapp-ontap.html
          - title: "NetApp storage systems overview"
            entries:
            - title: "Overview"
              url: /containers/rh-os-n_overview_netapp.html
            - title: "NetApp ONTAP and Openshift"
              url: /openshift/os-netapp-ontap.html
            - title: "NetApp Element"
              url: /openshift/os-netapp-element.html
          - title: "NetApp storage integration with Openshift"
            url: /openshift/os-storint-overview.html
          - title: "NetApp Trident overview"
            entries:
              - title: "Trident overview"
                url: /openshift/os-trident-overview.html
              - title: "NetApp ONTAP NFS"
                url: /openshift/os-trident-ontap-nfs.html
              - title: "NetApp ONTAP iSCSI"
                url: /openshift/os-trident-ontap-iscsi.html
              - title: "NetApp Element iSCSI"
                url: /openshift/os-trident-element-iscsi.html
    - section: containers
    - title: "Videos"
      entries:
        - title: "AWS hybrid cloud"
          url: /videos/hmc-aws-videos.html
        - title: "Azure hybrid cloud"
          url: /videos/hmc-azure-videos.html
        - title: "OpenShift hybrid cloud"
          url: /videos/hmc-openshift-videos.html

    - title: "Blogs"
      url: /blogs.html

    - title: "Legal notices"
      url: /legal-notices.html