settings:
  name: "NetApp container solutions"
  internal:
    pdf_enabled: true
    lipi_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: true
    lipi_enabled: true
  pdf: 
    gen-type: named-only
    zip-level: 1
    zip-filename: netapp-solutions-containers.zip

product-family:
  name: NetApp solutions
  repo: netapp-solutions-family

sidebar:
  entries:
    - title: "Container solutions"
      url: /index.html
    - title: "What's new"
      url: /whats-new.html
    - title: Get started
      entries:
          - title: "About NetApp storage"
            url: /anthos/anthos-netapp-overview.html
          - title: "About NetApp ONTAP"
            url: /anthos/anthos-netapp-ontap.html
    - section: containers

    - title: "Videos"
      entries:
        - title: "AWS hybrid cloud"
          url: /videos/hmc-aws-videos.html
        - title: "Azure hybrid cloud"
          url: /videos/hmc-azure-videos.html
        - title: "OpenShift hybrid cloud"
          url: /videos/hmc-openshift-videos.html

    - title: "Blogs"
      url: /blogs.html

    - title: "Legal notices"
      url: /legal-notices.html