---
sidebar: sidebar
permalink: vsphere-kubernetes-service/netapp-storage-vks.html
keywords: netapp, ONTAP, trident, persistent storage, kubernetes, vks
summary: "Learn about the key benefits of using NetApp ONTAP storage with VMware Kubernetes Service workloads."
---

= Learn about NetApp storage for VMware Kubernetes Service
:toc: macro
:hardbreaks:
:toclevels: 1
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ../media/

[.lead]
Using NetApp as storage for VMware Kubernetes Service (VKS) is a powerful combination that leverages NetApp's robust storage solutions to enhance the performance, scalability, and reliability of Kubernetes workloads. NetApp Trident, an open-source dynamic storage provisioner for Kubernetes, is used for integrating storage with workloads on VMware Kubernetes Service.

== Key benefits of using NetApp storage with VKS

. *Dynamic Storage Provisioning:* NetApp Trident allows for dynamic provisioning of storage volumes, enabling Kubernetes pods to request storage on-the-fly based on their requirements.

. *Persistent Storage:* NetApp solutions provide persistent storage capabilities, ensuring data durability and availability across pod restarts and failures.

. *High Performance:* NetApp's storage solutions, such as ONTAP, offer high-performance storage with low latency, which is ideal for I/O-intensive applications running on Kubernetes.

. *Scalability:* NetApp storage systems can scale to meet the demands of growing Kubernetes workloads, supporting large-scale deployments.

. *Data Management:* NetApp provides advanced data management features, including snapshots, cloning, and data replication, which can be beneficial for backup, disaster recovery, and development workflows.

. *Multi-Cloud and Hybrid Cloud Support:* NetApp's storage solutions can be deployed across on-premises, public cloud, and hybrid cloud environments, providing flexibility and consistency in storage management.

== NetApp ONTAP integration overview

NetApp ONTAP provides enterprise-grade storage with features like data deduplication, compression, and encryption. You use NetApp Trident to integrate NetApp storage with Kubernetes. NetApp Trident supports various NetApp storage platforms, including ONTAP on-premises, FSx for NetApp ONTAP in AWS, Azure NetApp Files in Azure, and Google Cloud NetApp Volumes in Google Cloud.

You use Trident Protect to handle data protection and disaster recovery for your Kubernetes workloads. Trident Protect allows you to create snapshots, clones, and replicate data across different storage backends, ensuring that your data is safe and recoverable in case of failures.

For additional information about NetApp Trident, refer to the official documentation: link:https://docs.netapp.com/us-en/trident/index.html[https://docs.netapp.com/us-en/trident/index.html^]